const KEY='deep-dive-studio-v2', $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const TOPICS=[
 {name:'Civic resilience',terms:['city','cities','urban','library','libraries','street','streets','walkable','neighborhood','public','civic','housing','transit','climate'],color:'#e57953',about:'How shared places and institutions shape collective resilience.'},
 {name:'Deliberate AI',terms:['ai','artificial','intelligence','llm','language','model','models','automation','automated','agent','agents','algorithm','algorithms','technology','judgment'],color:'#eab952',about:'Where intelligent tools help, hinder, or change human judgment.'},
 {name:'Systems thinking',terms:['system','systems','feedback','loop','loops','policy','policies','complex','complexity','default','defaults','incentive','incentives','governance'],color:'#4d8068',about:'The structures and feedback loops behind recurring problems.'}
];
const STOP=new Set('about after again also and are but can chat for from have how into just like more not one our out people search that the their then these this through to using was what when where which who why with you your');
const FALLBACK=[
 {id:'systems',title:'Thinking in Systems',source:'Book · Chelsea Green',description:'Donella Meadows’ guide to looking for leverage points in complex systems.',link:'https://www.chelseagreen.com/product/thinking-in-systems/',type:'book',terms:['systems','feedback','policy']},
 {id:'cities',title:'The Death and Life of Great American Cities',source:'Book · Vintage',description:'Jane Jacobs’ foundational account of diverse, walkable public life.',link:'https://www.penguinrandomhouse.com/books/292095/the-death-and-life-of-great-american-cities-by-jane-jacobs/',type:'book',terms:['city','urban','public','street']},
 {id:'human-ai',title:'Designing Human-Centered AI Experiences',source:'Article · Google PAIR',description:'A practical framework for keeping people in control of AI-assisted products.',link:'https://pair.withgoogle.com/guidebook-v2/',type:'report',terms:['ai','automation','human']}
];
let state=JSON.parse(localStorage.getItem(KEY)||'{}');Object.assign(state,{signals:state.signals||[],reads:state.reads||[],saved:state.saved||[],skipped:state.skipped||[],notes:state.notes||{},reflections:state.reflections||{}});
const persist=()=>localStorage.setItem(KEY,JSON.stringify(state)); const words=t=>(String(t).toLowerCase().match(/[a-z][a-z'-]{2,}/g)||[]).filter(w=>!STOP.has(w)); const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
$('#today-label').textContent=new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric'}).format(new Date());
function analyze(){const groups=new Map(TOPICS.map(t=>[t.name,{...t,signals:[]}])),unknown=[];state.signals.forEach(s=>{const w=words(s.text),best=TOPICS.map(t=>({t,score:t.terms.reduce((n,x)=>n+w.filter(y=>y===x||y.startsWith(x)).length,0)})).sort((a,b)=>b.score-a.score)[0];best.score?groups.get(best.t.name).signals.push(s):unknown.push(s)});if(unknown.length){const counts={};unknown.forEach(s=>words(s.text).forEach(w=>counts[w]=(counts[w]||0)+1));const term=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'questions';groups.set('Emerging inquiry',{name:'Emerging inquiry',terms:[term],color:'#7d6da8',about:`An early trail around “${term}”.`,signals:unknown})}return [...groups.values()].filter(t=>t.signals.length).sort((a,b)=>b.signals.length-a.signals.length)}
function notify(text){const n=$('#toast');n.textContent=text;n.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>n.classList.remove('show'),2800)}
function renderBrief(threads){const root=$('#briefing-content');if(!threads.length){root.innerHTML='<div class="brief-lines"><p>Add a few traces and Deep Dive will make a grounded weekly briefing from them.</p></div>';return}const first=threads[0],second=threads[1];root.innerHTML=`<div class="brief-lines"><p><b>${first.name}</b> is your strongest current thread.<small>${first.signals.length} signals point here — the question is gaining shape.</small></p>${second?`<p><b>${second.name}</b> is beginning to cross with it.<small>Try reading across both threads, not only inside each one.</small></p>`:''}<p><b>Open question:</b> what would change if you followed this thread for another week?<small>Use the notebook to keep the answer provisional.</small></p></div>`}
function renderTimeline(){const root=$('#timeline');root.innerHTML='';if(!state.signals.length){root.innerHTML='<div class="empty">Your intentionally saved searches, chats, notes, and pages will appear in time order.</div>';return}state.signals.slice().reverse().slice(0,8).forEach(s=>{const t=topicOf(s),node=document.createElement('article');node.className='trace';node.style.setProperty('--accent',t?.color||'#7d6da8');node.innerHTML=`<small>${esc(s.type)} · ${new Date(s.createdAt).toLocaleDateString()}</small>${esc(s.text)}`;root.append(node)})}
function topicOf(signal){return analyze().find(t=>t.signals.some(s=>s.id===signal.id))}
function openThread(t){$('#modal-title').textContent=t.name;$('#modal-description').textContent=t.about;$('#modal-signals').innerHTML=t.signals.slice().reverse().map(s=>`<article><small>${esc(s.type)} · ${new Date(s.createdAt).toLocaleDateString()}</small>${esc(s.text)}</article>`).join('');$('#thread-modal').showModal()}
function renderThreads(threads){const root=$('#thread-grid');root.innerHTML='';if(!threads.length){root.innerHTML='<div class="empty">Threads appear after you add activity. Every one can be opened to inspect the exact evidence behind it.</div>';return}threads.forEach(t=>{const node=$('#thread-template').content.cloneNode(true);node.querySelector('.thread-card').style.setProperty('--accent',t.color);node.querySelector('.thread-card small').textContent=`${t.signals.length} signal${t.signals.length===1?'':'s'}`;node.querySelector('h3').textContent=t.name;node.querySelector('p').textContent=t.about;node.querySelector('em').textContent=t.signals.length>2?'gaining momentum':'just surfaced';node.querySelector('button').onclick=()=>{renderNotebook(t.name);location.hash='notebook'};node.querySelector('.thread-card').ondblclick=()=>openThread(t);root.append(node)})}
function renderMap(threads){const root=$('#map');root.innerHTML='';threads.slice(0,4).forEach((t,i)=>{const n=document.createElement('button');n.className='map-node';n.style.setProperty('--accent',t.color);n.style.left=`${[50,23,77,50][i]}%`;n.style.top=`${[50,27,72,83][i]}%`;n.textContent=t.name;n.onclick=()=>openThread(t);root.append(n)})}
function renderNotebook(active){const threads=analyze(),tabs=$('#notebook-tabs');tabs.innerHTML='';if(!threads.length){$('#notebook-content').innerHTML='<div class="empty">A notebook opens when you have a thread to follow.</div>';return}const selected=threads.find(t=>t.name===active)||threads[0];threads.forEach(t=>{const b=document.createElement('button');b.textContent=t.name;b.classList.toggle('active',t.name===selected.name);b.onclick=()=>renderNotebook(t.name);tabs.append(b)});const saved=state.saved.filter(r=>score(r,[selected])>0);$('#notebook-content').innerHTML=`<h3>${esc(selected.name)}</h3><p class="helper">${esc(selected.about)}</p><h4>Open question</h4><textarea id="thread-note" placeholder="What are you trying to understand next?">${esc(state.notes[selected.name]||'')}</textarea><h4>Saved reading</h4><div class="saved-list">${saved.length?saved.map(r=>`<a href="${esc(r.link)}" target="_blank" rel="noreferrer">${esc(r.title)}</a>`).join('<br>'):'Save a reading that helps move this thread forward.'}</div>`;$('#thread-note').oninput=e=>{state.notes[selected.name]=e.target.value;persist()}}
function score(read,threads){const h=words(`${read.title} ${read.description||''}`);return threads.reduce((n,t)=>n+t.signals.length+t.terms.reduce((x,w)=>x+(h.includes(w)?4:0),0),0)+(state.saved.some(s=>s.terms?.some(w=>h.includes(w)))?2:0)}
function renderReading(threads){const root=$('#reading-list'),filter=$('#source-filter').value,mode=$('#reading-mode').value;let reads=state.reads.filter(r=>!state.skipped.includes(r.id));if(filter!=='all')reads=reads.filter(r=>r.type===filter);reads.sort((a,b)=>score(b,threads)-score(a,threads));root.innerHTML='';if(!reads.length){root.innerHTML='<div class="empty">Add activity and choose “Find reading.” The queue will explain its connection to your trail.</div>';return}reads.slice(0,7).forEach(r=>{const n=$('#reading-template').content.cloneNode(true),top=threads[0],saved=state.saved.some(s=>s.id===r.id);n.querySelector('small').textContent=r.source;const a=n.querySelector('a');a.href=r.link;a.textContent=r.title;n.querySelector('.description').textContent=r.description||'A source connected to your research trail.';n.querySelector('.why').textContent=`${mode==='challenge'?'A contrasting angle on':mode==='practical'?'A practical route into':mode==='academic'?'An academic source for':mode==='short'?'A concise starting point for':'An orientation to'} ${top?.name?.toLowerCase()||'your active threads'}${top?` (${top.signals.length} signals)`:''}.`;const save=n.querySelector('.save');save.textContent=saved?'Saved ✓':'Save';save.onclick=()=>{state.saved=saved?state.saved.filter(s=>s.id!==r.id):[...state.saved,r];persist();render();notify(saved?'Removed from saved reading.':'Saved — similar themes now rank higher.')};n.querySelector('.skip').onclick=()=>{state.skipped.push(r.id);persist();render();notify('Skipped — this kind of reading will recede.')};const reflection=n.querySelector('.reflection');n.querySelector('.reflect').onclick=()=>reflection.hidden=!reflection.hidden;const textarea=reflection.querySelector('textarea');textarea.value=state.reflections[r.id]||'';reflection.querySelector('button').onclick=()=>{state.reflections[r.id]=textarea.value;persist();notify('Reflection saved to your research story.')};root.append(n)})}
function render(){const threads=analyze();renderBrief(threads);renderTimeline();renderThreads(threads);renderMap(threads);renderNotebook();renderReading(threads)}
function add(records){const clean=records.map(r=>({id:crypto.randomUUID(),text:String(r.text||'').trim(),type:r.type||'import',createdAt:r.createdAt||new Date().toISOString()})).filter(r=>r.text);if(!clean.length)return 0;state.signals.push(...clean);persist();render();return clean.length}
function parse(content,name){try{if(name.endsWith('.json')){const data=JSON.parse(content);return(Array.isArray(data)?data:data.items||data.messages||[]).map(x=>({text:x.text||x.query||x.title||x.content,type:x.type||'import'}))}if(name.endsWith('.csv')){const [h,...rows]=content.split(/\r?\n/).filter(Boolean),heads=h.split(',').map(x=>x.trim().toLowerCase()),i=Math.max(heads.indexOf('text'),heads.indexOf('query'),heads.indexOf('title')),type=heads.indexOf('type');return rows.map(row=>{const c=row.split(',');return{text:c[i<0?0:i],type:c[type]||'import'}})}}catch{notify('That file could not be read. Try a simple text, CSV, or JSON export.');return[]}return content.split(/\r?\n/).filter(Boolean).map(text=>({text,type:'import'}))}
async function findReading(){const threads=analyze();if(!threads.length)return notify('Add at least one signal before finding reading.');const button=$('#refresh');button.disabled=true;button.textContent='Searching…';const mode=$('#reading-mode').value,query=`${threads.slice(0,2).flatMap(t=>t.terms.slice(0,4)).join(' ')} ${mode==='academic'?'research study':mode==='practical'?'case study':mode==='challenge'?'critique':''}`;try{const res=await fetch(`https://api.crossref.org/works?rows=14&select=DOI,title,container-title,abstract,type&query.bibliographic=${encodeURIComponent(query)}`);if(!res.ok)throw Error();state.reads=(await res.json()).message.items.filter(x=>x.DOI&&x.title?.[0]).map(x=>({id:`doi:${x.DOI}`,title:x.title[0],source:`${x.type||'Work'} · ${x['container-title']?.[0]||'Crossref'}`,description:(x.abstract||'').replace(/<[^>]+>/g,'').slice(0,320),link:`https://doi.org/${x.DOI}`,type:x.type,terms:words(`${x.title[0]} ${x.abstract||''}`)}));$('#source-note').textContent='Live Crossref results, ranked against your local themes and feedback.'}catch{state.reads=FALLBACK.map(x=>({...x}));$('#source-note').textContent='Crossref was unavailable, so Deep Dive is showing clearly marked fallback sources.'}persist();render();button.disabled=false;button.textContent='Find reading';notify('The reading queue has been refreshed.')}
function ask(question){const threads=analyze(),terms=words(question),matches=state.signals.filter(s=>terms.some(t=>words(s.text).includes(t))||terms.some(t=>topicOf(s)?.terms.includes(t))).slice(-3);const answer=$('#ask-answer');answer.hidden=false;if(!state.signals.length){answer.textContent='Your trail is empty. Add a search, chat excerpt, or saved page first.';return}const strongest=threads[0];answer.innerHTML=`<b>${esc(strongest.name)}</b> is the clearest thread in your current trail (${strongest.signals.length} signals). ${matches.length?`The closest evidence is: ${matches.map(s=>`“${esc(s.text.slice(0,110))}”`).join(' · ')}`:`I found no exact phrase match, so this is based on the strongest recurring thread rather than a precise claim.`}`}
function exportStory(){const threads=analyze();const md=`# My Deep Dive research story\n\nGenerated ${new Date().toLocaleDateString()}\n\n## Active threads\n${threads.map(t=>`- **${t.name}** — ${t.signals.length} signals\n  - Open question: ${state.notes[t.name]||'Not yet written'}`).join('\n')}\n\n## Saved reading\n${state.saved.map(r=>`- [${r.title}](${r.link})`).join('\n')||'- No saved reading yet'}\n\n## Reflections\n${Object.entries(state.reflections).map(([id,text])=>`- ${text}`).join('\n')||'- No reflections yet'}\n`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([md],{type:'text/markdown'}));a.download='deep-dive-research-story.md';a.click();URL.revokeObjectURL(a.href);notify('Your research story was exported.')}
$$('[data-open]').forEach(b=>b.onclick=()=>$('#'+b.dataset.open).showModal());$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$$('[data-panel]').forEach(x=>x.hidden=x.dataset.panel!==b.dataset.target)});
$('#activity-form').onsubmit=async e=>{e.preventDefault();const f=$('#activity-file').files[0];let records=[];if(f)records=parse(await f.text(),f.name.toLowerCase());else if($('#save-title').value||$('#save-url').value)records=[{text:`${$('#save-title').value} ${$('#save-note').value} ${$('#save-url').value}`,type:'bookmark'}];else records=$('#activity-text').value.split(/\r?\n/).filter(Boolean).map(text=>({text,type:$('#activity-type').value}));const n=add(records);if(n){$('#activity').close();e.target.reset();notify(`${n} trace${n===1?'':'s'} added to your private trail.`);findReading()}};$('#refresh').onclick=findReading;$('#reading-mode').onchange=render;$('#source-filter').onchange=render;$('#ask-form').onsubmit=e=>{e.preventDefault();ask($('#ask-input').value)};$('#export').onclick=exportStory;
$('#load-demo').onclick=()=>{if(state.signals.length&&!confirm('Add demo activity alongside your own trail?'))return;add([{text:'How do public libraries support climate resilience in walkable neighborhoods?',type:'search'},{text:'Compare transit-oriented development policies and public space design',type:'search'},{text:'In an LLM chat, explore useful friction in AI decision systems and human agency',type:'chat'},{text:'Notes on feedback loops, local policy defaults, and systems thinking',type:'note'},{text:'Examples of AI agents that preserve human judgment instead of automation bias',type:'chat'}]);findReading()};
try{const capture=JSON.parse(new URLSearchParams(location.search).get('capture'));if(capture?.title){add([{text:`${capture.title} ${capture.url}`,type:'bookmark'}]);history.replaceState({},'',location.pathname);notify('Page captured from the Deep Dive extension.')}}catch{}render();
